### ISSUE TITLE
No contact information

### ISSUE THREAD

**Issue by tuukka** [hugovk/helometer#1]
Just wanted to say thanks for creating this service and publishing the code as well as improvements to pybikes! Have you heard about the hackathon we are organising? You can register at http://reittiopas-hackathon.confetti.events/

**Comment by hugovk** [comment]
Thanks, I'll take a look!

**Comment by hugovk** [comment]
Unfortunately I couldn't make it this weekend but thanks for the invite and hope it's going well!
